{{- if .Values.coturn.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: coturn
  labels: { app: coturn }
spec:
  type: LoadBalancer
  selector: { app: coturn }
  ports:
    - { name: stun-udp, port: {{ .Values.coturn.stunPort }}, targetPort: stun-udp, protocol: UDP }
    - { name: stun-tcp, port: {{ .Values.coturn.stunPort }}, targetPort: stun-tcp, protocol: TCP }
    - { name: turn-tls, port: {{ .Values.coturn.turnTLSPort }}, targetPort: turn-tls, protocol: TCP }
{{- end }}
