#!/usr/bin/env bash
# chepherd one-command install
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/chepherd/chepherd/main/install.sh | bash
#   -- or --
#   ./install.sh [--port PORT] [--cwd DIR] [--no-start]
#
# What it does:
#   1. Checks for Go 1.22+
#   2. Clones / updates the repo into ~/src/chepherd
#   3. Builds the binary
#   4. Installs it to ~/.local/bin/chepherd
#   5. Installs the Astro web UI (npm install + build)
#   6. Creates a systemd user service (if available) or a start script
#   7. Starts chepherd and opens the browser

set -euo pipefail

REPO_URL="https://github.com/agenity-org/agenity.git"
INSTALL_DIR="$HOME/.local/bin"
STATE_DIR="$HOME/.local/state/chepherd"
SRC_DIR="$HOME/src/chepherd"
BIN_NAME="chepherd"
PORT="${CHEPHERD_PORT:-8080}"
CWD="${CHEPHERD_CWD:-$HOME}"
NO_START=0

# --- Parse args ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) PORT="$2"; shift 2 ;;
    --cwd)  CWD="$2";  shift 2 ;;
    --no-start) NO_START=1; shift ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

info()  { echo -e "\033[32m[chepherd]\033[0m $*"; }
warn()  { echo -e "\033[33m[chepherd]\033[0m $*"; }
error() { echo -e "\033[31m[chepherd]\033[0m $*" >&2; exit 1; }

# --- Check Go ---
if ! command -v go &>/dev/null; then
  error "Go is required but not found. Install from https://go.dev/dl/ then re-run."
fi
GO_VER=$(go version | grep -oP 'go\K[0-9]+\.[0-9]+' | head -1)
GO_MAJOR=$(echo "$GO_VER" | cut -d. -f1)
GO_MINOR=$(echo "$GO_VER" | cut -d. -f2)
if [[ "$GO_MAJOR" -lt 1 ]] || [[ "$GO_MAJOR" -eq 1 && "$GO_MINOR" -lt 22 ]]; then
  error "Go 1.22+ required (found $GO_VER). Update from https://go.dev/dl/"
fi
info "Go $GO_VER found"

# --- Check Node (optional — for web UI) ---
HAS_NODE=0
if command -v node &>/dev/null && command -v npm &>/dev/null; then
  HAS_NODE=1
  info "Node $(node --version) found — web UI will be built"
else
  warn "Node/npm not found — web UI will not be installed. Install Node 20+ for the dashboard."
fi

# --- Clone or update repo ---
mkdir -p "$HOME/src"
if [[ -d "$SRC_DIR/.git" ]]; then
  info "Updating repo at $SRC_DIR"
  git -C "$SRC_DIR" pull --ff-only
else
  info "Cloning chepherd into $SRC_DIR"
  git clone "$REPO_URL" "$SRC_DIR"
fi

# --- Build binary ---
info "Building chepherd..."
cd "$SRC_DIR"
go build -ldflags="-s -w" -o "/tmp/chepherd-install-$$" .
info "Build ok"

# --- Install binary ---
mkdir -p "$INSTALL_DIR"
mv "/tmp/chepherd-install-$$" "$INSTALL_DIR/$BIN_NAME"
chmod +x "$INSTALL_DIR/$BIN_NAME"
info "Installed → $INSTALL_DIR/$BIN_NAME"

# --- PATH hint ---
if ! echo "$PATH" | grep -q "$INSTALL_DIR"; then
  warn "$INSTALL_DIR is not in your PATH."
  warn "Add this to your ~/.bashrc or ~/.zshrc:"
  warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# --- Build web UI ---
if [[ "$HAS_NODE" -eq 1 ]]; then
  info "Installing web UI dependencies..."
  cd "$SRC_DIR/web"
  npm install --silent
  npm run build --silent
  info "Web UI built"
fi

# --- Create state dir ---
mkdir -p "$STATE_DIR"

# --- systemd user service (if available) ---
SYSTEMD_DIR="$HOME/.config/systemd/user"
if command -v systemctl &>/dev/null && systemctl --user status &>/dev/null 2>&1; then
  mkdir -p "$SYSTEMD_DIR"
  cat > "$SYSTEMD_DIR/chepherd.service" <<UNIT
[Unit]
Description=chepherd multi-agent runtime
After=network.target

[Service]
ExecStart=$INSTALL_DIR/$BIN_NAME run --cwd $CWD --headless --listen 127.0.0.1:$PORT --state-dir $STATE_DIR
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
UNIT
  systemctl --user daemon-reload
  systemctl --user enable chepherd.service
  info "Systemd user service installed: systemctl --user start|stop chepherd"
fi

# --- Start script fallback ---
START_SCRIPT="$HOME/.local/bin/chepherd-start"
cat > "$START_SCRIPT" <<SCRIPT
#!/usr/bin/env bash
# Auto-generated by chepherd install.sh
nohup "$INSTALL_DIR/$BIN_NAME" run --cwd "$CWD" --headless --listen 127.0.0.1:$PORT --state-dir "$STATE_DIR" > "$STATE_DIR/runtime.log" 2>&1 &
echo "chepherd started — dashboard at http://127.0.0.1:$PORT"
SCRIPT
chmod +x "$START_SCRIPT"

# --- Start ---
if [[ "$NO_START" -eq 0 ]]; then
  # Stop any existing instance
  pkill -f "$BIN_NAME run" 2>/dev/null || true
  sleep 1
  info "Starting chepherd on http://127.0.0.1:$PORT ..."
  nohup "$INSTALL_DIR/$BIN_NAME" run --cwd "$CWD" --headless --listen "127.0.0.1:$PORT" --state-dir "$STATE_DIR" > "$STATE_DIR/runtime.log" 2>&1 &
  sleep 3
  if curl -sf "http://127.0.0.1:$PORT/healthz" &>/dev/null; then
    info "Runtime is up."
    if [[ "$HAS_NODE" -eq 1 ]]; then
      # Start Astro dev server for the dashboard
      cd "$SRC_DIR/web"
      nohup npm run dev -- --port 4321 > "$STATE_DIR/web.log" 2>&1 &
      sleep 3
      info "Dashboard at http://localhost:4321"
      if command -v xdg-open &>/dev/null; then
        xdg-open "http://localhost:4321" &>/dev/null || true
      elif command -v open &>/dev/null; then
        open "http://localhost:4321" || true
      fi
    fi
  else
    warn "Runtime did not respond at $PORT. Check $STATE_DIR/runtime.log"
  fi
fi

echo ""
info "Installation complete."
info "  Binary:   $INSTALL_DIR/$BIN_NAME"
info "  State:    $STATE_DIR"
info "  Start:    $START_SCRIPT"
if command -v systemctl &>/dev/null; then
  info "  Service:  systemctl --user start chepherd"
fi
